wandb_version: 1

dataset:
  desc: null
  value: reddit
epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689815420.000092
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 76
      - 77
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.5
      8:
      - 5
